version: 0.2
env:
  variables:
    S3_BUCKET: "emisexamsstg"
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --configuration=staging --aot
  post_build:
     commands:
      - aws s3 sync ./dist s3://${S3_BUCKET} --acl 'public-read' --delete
      - echo Build completed on `date`
